FROM gitpod/workspace-full

USER gitpod
ENV HOME=/home/gitpod

# install deno
ENV DENO_INSTALL=${HOME}/.deno
RUN mkdir -p ${DENO_INSTALL} \
    && curl -fsSL https://deno.land/x/install/install.sh | sh

ENV PATH=${DENO_INSTALL}/bin:${PATH} \
    DENO_DIR=${DENO_INSTALL}/.cache/deno

RUN ${DENO_INSTALL}/bin/deno completions bash > /home/gitpod/.bashrc.d/90-deno